---
client:
  rate: 20

display:
  # use defaults...

world:
  n_random_vehicles: 200
  n_random_walkers: 0

recorder:
  record_truth: false

infrastructure:
  # use defaults...

ego:
  idx_spawn: 'randint'
  idx_vehicle: 0
  idx_destination: null
  roaming: false
  autopilot: true
  respawn_on_done: true
  max_speed: 20  # m/s
  sensors:
    - camera 0:
        name: 'camera'
        save: false
    - gnss 0:
        name: 'gnss'
        save: false
    - imu 0:
        name: 'imu'
        save: false