---
client:
  rate: 20

display:
  # use defaults...

world:
  n_random_vehicles: 30
  n_random_walkers: 0
  placed_agents:
    npc 0:
      type: 'vehicle'
      idx_spawn: 10
      idx_vehicle: 5
      autopilot: true
      delta_spawn:
        x: 20
        y: 0
        z: 0
    npc 1:
      type: 'vehicle'
      idx_spawn: 10
      idx_vehicle: 5
      autopilot: true
      delta_spawn:
        x: 30
        y: 10
        z: 0

recorder:
  record_truth: false

infrastructure:
  # use defaults...

ego:
  idx_spawn: 10
  idx_vehicle: 0
  idx_destination: null
  roaming: false
  autopilot: true
  respawn_on_done: true
  max_speed: 20  # m/s
  sensors:
    - camera 0:
        name: 'camera'
        save: false
    - camera 1:
        name: 'camera'
        save: false
        transform:
          location:
            x: -1.5
          rotation:
            yaw: -180
    - gnss 0:
        name: 'gnss'
        save: false
    - imu 0:
        name: 'imu'
        save: false