---
cameras:
  n_spawn: 0
  sensor_name: 'camera'
  name_prefix: 'CAM_INFRASTRUCTURE'
  seed: 10
  add_random_yaw: true
  idx_spawn: 'within-10-50'
  idx_spawn_list: [1, 10, 20, 5, 8, 15, 18, 6, 17, 60, 43, 35, 28, 19, 54, 44, 2, 23, 22, 31]
  comm_range: 50
  position_uncertainty:
    x: 0.0001
    y: 0.0001
    z: 0.0001
  save: false
  attributes:
    sensor_tick: 0.5
    fov: 90
    image_size_x: 1600
    image_size_y: 900
  noise: {}
  transform:
    location:
      x: 0
      y: 0
      z: 15  # up in the air
    rotation:
      pitch: -30
      yaw: 0
      roll: 0

depthcams:
  n_spawn: 0
  sensor_name: 'depthcam'
  name_prefix: 'CAM_DEPTH_INFRASTRUCTURE'
  seed: 10
  add_random_yaw: true
  idx_spawn: 'within-10-50'
  idx_spawn_list: [1, 10, 20, 5, 8, 15, 18, 6, 17, 60, 43, 35, 28, 19, 54, 44, 2, 23, 22, 31]
  comm_range: 50
  position_uncertainty:
    x: 0.0001
    y: 0.0001
    z: 0.0001
  save: false
  attributes:
    sensor_tick: 0.5
    fov: 90
    image_size_x: 1600
    image_size_y: 900
  noise: {}
  transform:
    location:
      x: 0
      y: 0
      z: 15  # up in the air
    rotation:
      pitch: -30
      yaw: 0
      roll: 0

lidars:
  n_spawn: 0
  sensor_name: 'lidar'
  name_prefix: 'LIDAR_INFRASTRUCTURE'
  seed: 10
  add_random_yaw: true
  idx_spawn: 'within-10-50'
  idx_spawn_list: [1, 10, 20, 5, 8, 15, 18, 6, 17, 60, 43, 35, 28, 19, 54, 44, 2, 23, 22, 31]
  spawn_loc: 'anywhere'
  comm_range: 50
  save: false
  mode: 'standard'
  position_uncertainty:
    x: 0.0001
    y: 0.0001
    z: 0.0001
  attributes:
    sensor_tick: 0.5  # slower for infrastructure
    channels: 64
    rotation_frequency: 20  # should be the same as simulation rate!
    range: 150.0
    points_per_second: 2120000  # 56,000*20*2 - note this scales rot freq
    upper_fov: 30  # degrees
    lower_fov: -25  # degrees
    horizontal_fov: 90
  transform:
    location:
      x: 0
      y: 0
      z: 15  # up in the air
    rotation:
      pitch: -30
      yaw: 0
      roll: 0

radars:
  n_spawn: 0
  sensor_name: 'radar'
  name_prefix: 'RADAR_INFRASTRUCTURE'
  seed: 10
  add_random_yaw: true
  idx_spawn: 'within-10-50'
  idx_spawn_list: [1, 10, 20, 5, 8, 15, 18, 6, 17, 60, 43, 35, 28, 19, 54, 44, 2, 23, 22, 31]
  spawn_loc: 'anywhere'
  comm_range: 30
  save: false
  position_uncertainty:
    x: 0.0001
    y: 0.0001
    z: 0.0001
  attributes:
    sensor_tick: 0.10
    horizontal_fov: 30.0
    vertical_fov: 30.0
    points_per_second: 1500
    range: 100.0
  transform:
    location:
      x: 0
      y: 0
      z: 15  # up in the air
    rotation:
      pitch: -30
      yaw: 0
      roll: 0
