---
enabled: true
disp_x: 1000
disp_y: 600
sensors:
  - camera hud 0:
      name: 'camera-hud-0'
      attributes:
        image_size_x: 1000  # ideally same as above values
        image_size_y: 600
      transform:
        location:
          x: -8.5
          y: 0
          z: 3.5
  - camera hud 1:
      name: 'camera-hud-1'
      attributes:
        image_size_x: 1000  # ideally same as above values
        image_size_y: 600
      transform:
        location:
          x: 0
          y: 0
          z: 15
        rotation:
          pitch: -90
          yaw: 0
          roll: 0